package com.example.fairplayfairrule.resourcepack;

public enum ValidationFailureCode {
    NONE,
    MALFORMED_MANIFEST,
    OVERSIZED_MANIFEST,
    INVALID_HASH,
    DUPLICATE_HASH,
    DUPLICATE_MANIFEST_ENTRY,
    DIRECTORY_NOT_SUPPORTED,
    UNRESOLVED_PACK,
    MISSING_REQUIRED_PACK,
    UNAPPROVED_PACK,
    WRONG_PLAYER_APPROVAL,
    UNAPPROVED_SERVER_PACK,
    BANNED_PACK,
    SESSION_PACK_ADDED,
    SESSION_PACK_REMOVED,
    SESSION_PACK_MODIFIED,
    SESSION_PACK_ORDER_CHANGED,
    SESSION_STATE_CHANGED
}
